#!/bin/bash

# Info: rofi-locate is a script to search local files and folders on your computer using the locate command and the updatedb database
# Requirements: rofi mlocate
# Playlist: rofi      https://www.youtube.com/playlist?list=PLqv94xWU9zZ0LVP1SEFQsLEYjZC_SUB3m

xdg-open "$(locate home media | rofi -threads 0 -width 100 -dmenu -i -p 'file')"

