#!/bin/sh
#
# elvis: rt		-- Search movie score using Rotten Tomatoes (https://www.rottentomatoes.com/)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search movie score using Rotten Tomatoes (https://www.rottentomatoes.com/)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://www.rottentomatoes.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.rottentomatoes.com/search/?search=${escaped_args}"
fi
