#!/bin/sh
#
# elvis: talos		-- Search Talos (www.talosintelligence.com/)
. surfraw || exit 1

w3_usage_hook () {
    cat <<-EOF
		Usage: $w3_argv0 [options] [search words]...
		Description:
		  Search Talos (www.talosintelligence.com/) to get the reputation of a website
		EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://www.talosintelligence.com/reputation_center/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.talosintelligence.com/reputation_center/lookup?search=${escaped_args}"
fi
