#!/bin/sh
#
# elvis: wallhaven		-- Search wallpapers using wallhaven (https://alpha.wallhaven.cc/)
. surfraw || exit 1

w3_usage_hook () {
    cat <<-EOF
		Usage: $w3_argv0 [options] [search words]...
		Description:
		  Search wallpapers using wallhaven (https://alpha.wallhaven.cc/)
		EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://alpha.wallhaven.cc/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://alpha.wallhaven.cc/search?q=${escaped_args}"
fi
