#!/bin/sh
#
# elvis: Wikipedia FR		-- Search general info using Wikipedia FR (https://fr.wikipedia.org)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search general info using Wikipedia FR (https://fr.wikipedia.org)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://fr.wikipedia.org"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://fr.wikipedia.org/w/index.php?title=Spécial:Recherche&profile=default&fulltext=Search&search=${escaped_args}"
fi
